// Posts the weekly MKDb status update to the #mank channel of the Metropolis
// Discord server, as the bot. Runs weekly from cron right after the Letterboxd
// lists are updated (see scripts/mkdb.crontab).
//
// The post is a single message with the standard text body + five image
// attachments (top ranked, risers, fallers, new entries, new departures),
// generated by scripts/weekly-images.ts.
//
// Auth: DISCORD_TOKEN (the mankbot bot token, same one discord-bot uses).
// Posting is done via the raw Discord REST API so the main project doesn't
// need discord.js as a dependency.
//
// Flags:
//   --dry-run   generate images + print the message, but don't post; writes
//               the images to /tmp/weekly-out for inspection.

import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import pool from '../db/conn.js';
import { generateWeeklyImages, fetchCurrentWeek } from './weekly-images.js';

const CHANNEL_ID = process.env.MANK_CHANNEL_ID || '1286092918762770462';
const TOKEN = process.env.DISCORD_TOKEN;
const METRO_LIST_SHORTLINK = 'https://boxd.it/HRGYm';   // letterboxd.com/samah_/list/mkdb-top-1000/

function buildContent(week: number): string {
    return (
        `MKDb Week ${week} is now live: [mkdb.co](https://mkdb.co)\n\n` +
        `list has been updated on letterboxd: ${METRO_LIST_SHORTLINK}`
    );
}

async function postToDiscord(content: string, images: { filename: string; buffer: Buffer }[]): Promise<void> {
    if (!TOKEN) throw new Error('DISCORD_TOKEN must be set to post the weekly update');

    const form = new FormData();
    form.append('payload_json', JSON.stringify({ content, allowed_mentions: { parse: [] } }));
    images.forEach((img, i) => {
        // Wrap in a fresh Uint8Array so the BlobPart type is a plain
        // ArrayBuffer view (Node's Buffer is ArrayBufferLike, which the DOM
        // Blob typings reject).
        form.append(`files[${i}]`, new Blob([new Uint8Array(img.buffer)], { type: 'image/jpeg' }), img.filename);
    });

    const res = await fetch(`https://discord.com/api/v10/channels/${CHANNEL_ID}/messages`, {
        method: 'POST',
        headers: { Authorization: `Bot ${TOKEN}` },
        body: form,
    });
    if (!res.ok) {
        throw new Error(`Discord POST failed: ${res.status} ${await res.text()}`);
    }
    const msg = await res.json() as { id: string };
    console.log(`[weekly-post] posted message ${msg.id} to channel ${CHANNEL_ID}`);
}

async function main() {
    const dryRun = process.argv.includes('--dry-run');
    const t0 = Date.now();
    console.log(`[weekly-post] start at ${new Date().toLocaleString('en-US', { timeZone: 'America/New_York' })} ET${dryRun ? ' (DRY RUN)' : ''}`);

    const week = await fetchCurrentWeek();
    const content = buildContent(week);
    console.log(`[weekly-post] week ${week}. message:\n---\n${content}\n---`);

    console.log('[weekly-post] generating 5 images...');
    const images = await generateWeeklyImages();
    for (const img of images) console.log(`[weekly-post]   ${img.filename}: ${img.buffer.length} bytes`);

    if (dryRun) {
        const outDir = '/tmp/weekly-out';
        fs.mkdirSync(outDir, { recursive: true });
        for (const img of images) fs.writeFileSync(path.join(outDir, img.filename), img.buffer);
        console.log(`[weekly-post] DRY RUN — wrote images to ${outDir}, not posting`);
        return;
    }

    await postToDiscord(content, images);
    const dur = Math.floor((Date.now() - t0) / 1000);
    console.log(`[weekly-post] done in ${Math.floor(dur / 60)}m ${dur % 60}s`);
}

main()
    .then(() => pool.end())
    .catch((err) => {
        console.error('[weekly-post] FATAL:', err);
        pool.end().finally(() => process.exit(1));
    });
